name:                BBS
version:             0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  BBS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BBS

tests:
  BBS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BBS
